# Generated by Django 2.2.19 on 2021-07-25 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20210725_0923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'default_related_name': 'posts', 'ordering': ['-pub_date'], 'verbose_name_plural': 'Посты'},
        ),
    ]
